server:
  port: 0

spring:
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    path: /timeline-service/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

services:
  profile:
    name: profile-service
  tweet:
    name: tweet-service
