server:
  port: 0

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Profile
      authentication-database: admin
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

feign:
  auth-client:
    name: authentication-service
