server:
  port: 0

spring:
  data:
    mongodb:
      username: "{cipher}AQBtl+aTM9NX6IqcT6kOrr7d2L6LE5G05dXDxBRH08xBxNyyYG6R3UsNthAHhfKOwO8KaS8S6DmYWSDQoRKEvB0AN8ri4aftXI562BXNzBXXq7i/SKOmem9J5d2KPsiQ4RGylrSYlD3jEOl1CJtlKPnNF8lrF78J8pEIiZvpzzbPnlcvaXT3GGkOSVD28rAcORmk07009DoyVYScNrMYv6XQyB8c2qLWSBLPyRFnZBzWyC7QDZt2TJr9zORIL34l4lFrIvY33cd2eUFQwXRt2vT+ugwZmncja7m6PaEIYB2dOcNgrTaY5njvPytMk3HGLQEv+YCU1CopnAnqLajZvDEHfw5fJqd2zZ5CE1CYmFz8b++8ykBrUz38RrCFLL0nfC8="
      password: "{cipher}AQCaytRza17YGbcb8+xJPfze1NfOw/EVQqRCoC65xsGi3JTSb0ynelQ5ocJ9ZRF8D5/J4tjhMvBW/MQnCMS+fHNcoJ+6crZ+PWqn7SndYnboELtxzr8YLJ+KBDdaflFcK3mgJ8oIKgBuM7KS7gHYAX18ysUA2e0u4OEFnsjhPINdBDwlb0osoWw410h2xfKoJAr5LBo38fGPD9T1+Xx8NQbYCU686C4ePhZx7Ur1rFLlM0m0l63MvC8VJNp6pCd1SA3tjOBhsRUulgFr2GfiOLcOVybOmu8EpoW5L+ITD0w57lvBVdlurL7xvn0XfrespNy+uWURFN6QZoBFVl5sc1JXOj/cC6oxfcX1+VhnNTNvPL4GDJXKY/+bnNlTqka18kc="
      host: localhost
      port: 27017
      database: Profile
      authentication-database: admin
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

feign:
  auth-client:
    name: authentication-service
