server:
  port: 8081

spring:
  data:
    mongodb:
      host: mongo
    redis:
      host: redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
