server:
  port: 0

cloud:
  aws:
    credentials:
      access-key: "{cipher}AQC0ZMgQZr011mBsqqWPiALEqMKnx2bj/rfJCbDIDLrYPqFBNgSLhJt2PoMwdmDNXxcsxVlBqJ165D0fOrYWEOP88QYxSakCYI8Xfjo1X97N+21T4pt5LBhtwHM+uZZHYkPvbXfDIIjIY+ArqAoFVR9/la6n4CscqS19/QewxPXoX9uPlV+f1XjzEId21Hcvt1tSuncWnwT1SrxjqSeJKQDGRx/HYriN53n4moknOVcMB5zOVzZCWZP/NMARROJPbvL5baXyNsMkdQ3bS+yWnqhN7a6iziAgjih27j6CHxEX1cFPMy0t5GNC+gSQkZHFt57gCvpgb+afxpdTrZfrTNfcaFrJFSPfTHxeVa9K/TSo0bpLW280dYez1jTdVY/uwfolM8I3XbdrD6+eO+1qct7F"
      secret-key: "{cipher}AQBNmNdtir99JH6WVBafgHkhWDn5+CjhqhA6jgEs4Lr4wH4X+NOknZTYRyGOH61FhwyV4R0BU3RsyCPBYqnSsFIxFL5GPQBllA/h8busMuaA0I3VA1hXdDNtAgEsiuIZvc1N1y+L0zG+zn5NJWE39+OsKUj8KM2boiSvHtDoS6dQIXIRD3a14yJVuj2I7dPnAC3gSzvqQkqlQWIfYvo5onWK4JxZvnaQOyc/QaMKWoQ1raHS6SBf9OCJpyHsQN5oCQQ5oKNg9LGDGGQzMasmVKwDnn0GTrGGHCdOi0b5Onqi4ZHLqAl1I4otEC9q4c2/6JJu5j3ATwgEUdfrPPLJlkPGUrcDj5/Ds7/QFKVqMZe/f8bo+Jitm/PjxFiTpGg6WWu5lnkqWN6SvNVer7qnGH0ZkQf6zicvHuKnPj5BmD1TBQ=="
    region:
      static: us-east-1
    stack:
      auto: false
application:
  bucket:
    name: twitter-clone-storages

spring:
  data:
    mongodb:
      username: "{cipher}AQASAiBwNL6Ti1cQXfkZOJMRK4eEkQCikT4Ez/r9Ztp1oyIVZ6JmdcRUIqW2V1ZoOaaCI4CGYc31tIariNnOHB6byimVIWvDIT0lpBpqu0HNwgZQ7j8CJTBSBVnj2e1Vu0T56d15OMRShe0cDdsA83enyMU9XN6c/k1tHO2qm15gCjrpJcDhKvXgtluvp5W+44zzC7S1ZCRgGJI2Nj0u5K3p/dSlyUkcXBwXxzj8I2DTkSQMZBM/1LxSUKYh8esA9nDaHbUqNR4JZDhMuGPFZ28FD0LmTrZ3EmdapFhJu1FaIDXDjRjShfHauqjFZqKA5qEnSHBhuB+RT81s8yqks1eL2qv2jjB6sUas2vgzU23d8vH/MaDYbBdReN2D/yfMLSw="
      password: "{cipher}AQAqmlyMtbq6HvDxhwesdpQbQVF/O/aPYOO3Eeb2butTHJ3ODdRJ/Ij/XWLG0WbmJI+XACW6sVOPxDM2NQ/DhGm5cV0OOhrQOcNwVn3dzy6PGvRgHlk+FyaEQgdsL2H8V2Duyj6pKiXbR+9MWF4aPJheWJ+O3OPmyOP+jzg6LAFOTlHwNWALZw8SqlkhgFVGIAtg5tdLl0Q+E9vzC1lV70ez2sLufyZZUNgZu7pJ7WGEwh/wgtLuDV8FTT4r/nK4Lwunoj7C68WTZoZmXPk10JScZPR047O+pRs/btRJNfDI1Dio+PbeVMCXiIJMGW84U566Tv7fiLngMPwXTQi4Y3Dw5hm80jW486BabfVO9x7X9ZMEGfA3sAUGMRWnm0HX+Lw="
      host: localhost
      port: 27017
      database: Profile
      authentication-database: admin
      auto-index-creation: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

springdoc:
  api-docs:
    path: /profile-service/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

services:
  auth:
    name: authentication-service
