server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres-tweet-service:5431/tweet-service
  data:
    redis:
      host: redis

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
